// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import type {
  DeleteApiTodosByIdData,
  DeleteApiTodosByIdErrors,
  DeleteApiTodosByIdResponses,
  GetApiHealthData,
  GetApiHealthErrors,
  GetApiHealthResponses,
  GetApiTodosByIdData,
  GetApiTodosByIdErrors,
  GetApiTodosByIdResponses,
  GetApiTodosData,
  GetApiTodosErrors,
  GetApiTodosResponses,
  PostApiTodosData,
  PostApiTodosErrors,
  PostApiTodosResponses,
  PutApiTodosByIdData,
  PutApiTodosByIdErrors,
  PutApiTodosByIdResponses,
} from "./types.gen";

import { client } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health check endpoint
 *
 * Returns OK if the server is running
 */
export const getApiHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiHealthData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiHealthResponses,
    GetApiHealthErrors,
    ThrowOnError
  >({ url: "/api/health", ...options });

/**
 * Get all todos
 *
 * Retrieve a list of all todo items
 */
export const getApiTodos = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiTodosData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiTodosResponses,
    GetApiTodosErrors,
    ThrowOnError
  >({ url: "/api/todos", ...options });

/**
 * Create a new todo
 *
 * Create a new todo item
 */
export const postApiTodos = <ThrowOnError extends boolean = false>(
  options: Options<PostApiTodosData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiTodosResponses,
    PostApiTodosErrors,
    ThrowOnError
  >({
    url: "/api/todos",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a todo
 *
 * Delete a todo item by its ID
 */
export const deleteApiTodosById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiTodosByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiTodosByIdResponses,
    DeleteApiTodosByIdErrors,
    ThrowOnError
  >({ url: "/api/todos/{id}", ...options });

/**
 * Get a todo by ID
 *
 * Retrieve a todo item by its ID
 */
export const getApiTodosById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiTodosByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiTodosByIdResponses,
    GetApiTodosByIdErrors,
    ThrowOnError
  >({ url: "/api/todos/{id}", ...options });

/**
 * Update a todo
 *
 * Update an existing todo item by its ID
 */
export const putApiTodosById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiTodosByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutApiTodosByIdResponses,
    PutApiTodosByIdErrors,
    ThrowOnError
  >({
    url: "/api/todos/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
