// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiV1TodosByIdData, DeleteApiV1TodosByIdErrors, DeleteApiV1TodosByIdResponses, GetApiV1HealthData, GetApiV1HealthResponses, GetApiV1TodosByIdData, GetApiV1TodosByIdErrors, GetApiV1TodosByIdResponses, GetApiV1TodosData, GetApiV1TodosResponses, PostApiV1TodosData, PostApiV1TodosErrors, PostApiV1TodosResponses, PutApiV1TodosByIdData, PutApiV1TodosByIdErrors, PutApiV1TodosByIdResponses } from './types.gen';
import { z_delete_api_v1_todos_by_id_path, z_get_api_v1_todos_by_id_path, z_post_api_v1_todos_body, z_put_api_v1_todos_by_id_body, z_put_api_v1_todos_by_id_path } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiV1Health = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1HealthData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1HealthResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/health',
    ...options
});

export const getApiV1Todos = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1TodosData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1TodosResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/todos',
    ...options
});

export const postApiV1Todos = <ThrowOnError extends boolean = false>(options: Options<PostApiV1TodosData, ThrowOnError>) => (options.client ?? client).post<PostApiV1TodosResponses, PostApiV1TodosErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z_post_api_v1_todos_body,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/todos',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiV1TodosById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiV1TodosByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiV1TodosByIdResponses, DeleteApiV1TodosByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z_delete_api_v1_todos_by_id_path,
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/todos/{id}',
    ...options
});

export const getApiV1TodosById = <ThrowOnError extends boolean = false>(options: Options<GetApiV1TodosByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiV1TodosByIdResponses, GetApiV1TodosByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z_get_api_v1_todos_by_id_path,
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/todos/{id}',
    ...options
});

export const putApiV1TodosById = <ThrowOnError extends boolean = false>(options: Options<PutApiV1TodosByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiV1TodosByIdResponses, PutApiV1TodosByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z_put_api_v1_todos_by_id_body,
        path: z_put_api_v1_todos_by_id_path,
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/todos/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
