// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type ServerInternalSchemasCreateTodoRequest = {
    actualHours?: number;
    cost?: number;
    dueDate?: string;
    estimatedHours?: number;
    label?: string;
    priority?: ServerInternalSchemasTodoPriority;
    progress?: number;
    status?: ServerInternalSchemasTodoStatus;
    text: string;
};

export type ServerInternalSchemasHealthResponse = {
    arch?: string;
    args?: Array<string>;
    date?: string;
    memory?: {
        [key: string]: unknown;
    };
    node?: string;
    os?: string;
    status?: string;
    timezone?: string;
    timezoneName?: string;
    timezoneOffset?: number;
    uptime?: number;
    version?: string;
};

export type ServerInternalSchemasTodo = {
    actualHours?: number;
    completedAt?: string;
    cost?: number;
    createdAt?: string;
    dueDate?: string;
    estimatedHours?: number;
    id?: string;
    label?: string;
    priority?: ServerInternalSchemasTodoPriority;
    progress?: number;
    status?: ServerInternalSchemasTodoStatus;
    text?: string;
    updatedAt?: string;
};

export type ServerInternalSchemasTodoPriority = 'low' | 'medium' | 'high';

export type ServerInternalSchemasTodoStatus = 'backlog' | 'todo' | 'in_progress' | 'done' | 'canceled';

export type ServerInternalSchemasUpdateTodoRequest = {
    actualHours?: number;
    completedAt?: string;
    cost?: number;
    dueDate?: string;
    estimatedHours?: number;
    label?: string;
    priority?: ServerInternalSchemasTodoPriority;
    progress?: number;
    status?: ServerInternalSchemasTodoStatus;
    text?: string;
};

export type GetApiV1HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type GetApiV1HealthResponses = {
    /**
     * OK
     */
    200: ServerInternalSchemasHealthResponse;
};

export type GetApiV1HealthResponse = GetApiV1HealthResponses[keyof GetApiV1HealthResponses];

export type GetApiV1TodosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/todos';
};

export type GetApiV1TodosResponses = {
    /**
     * OK
     */
    200: Array<ServerInternalSchemasTodo>;
};

export type GetApiV1TodosResponse = GetApiV1TodosResponses[keyof GetApiV1TodosResponses];

export type PostApiV1TodosData = {
    /**
     * Todo creation request
     */
    body: ServerInternalSchemasCreateTodoRequest;
    path?: never;
    query?: never;
    url: '/api/v1/todos';
};

export type PostApiV1TodosErrors = {
    /**
     * Invalid request body or missing text
     */
    400: string;
};

export type PostApiV1TodosError = PostApiV1TodosErrors[keyof PostApiV1TodosErrors];

export type PostApiV1TodosResponses = {
    /**
     * Created
     */
    201: ServerInternalSchemasTodo;
};

export type PostApiV1TodosResponse = PostApiV1TodosResponses[keyof PostApiV1TodosResponses];

export type DeleteApiV1TodosByIdData = {
    body?: never;
    path: {
        /**
         * Todo ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/todos/{id}';
};

export type DeleteApiV1TodosByIdErrors = {
    /**
     * Invalid ID
     */
    400: string;
    /**
     * Todo not found
     */
    404: string;
};

export type DeleteApiV1TodosByIdError = DeleteApiV1TodosByIdErrors[keyof DeleteApiV1TodosByIdErrors];

export type DeleteApiV1TodosByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetApiV1TodosByIdData = {
    body?: never;
    path: {
        /**
         * Todo ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/todos/{id}';
};

export type GetApiV1TodosByIdErrors = {
    /**
     * Invalid ID
     */
    400: string;
    /**
     * Todo not found
     */
    404: string;
};

export type GetApiV1TodosByIdError = GetApiV1TodosByIdErrors[keyof GetApiV1TodosByIdErrors];

export type GetApiV1TodosByIdResponses = {
    /**
     * OK
     */
    200: ServerInternalSchemasTodo;
};

export type GetApiV1TodosByIdResponse = GetApiV1TodosByIdResponses[keyof GetApiV1TodosByIdResponses];

export type PutApiV1TodosByIdData = {
    /**
     * Todo update request
     */
    body: ServerInternalSchemasUpdateTodoRequest;
    path: {
        /**
         * Todo ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/todos/{id}';
};

export type PutApiV1TodosByIdErrors = {
    /**
     * Invalid ID or request body
     */
    400: string;
    /**
     * Todo not found
     */
    404: string;
};

export type PutApiV1TodosByIdError = PutApiV1TodosByIdErrors[keyof PutApiV1TodosByIdErrors];

export type PutApiV1TodosByIdResponses = {
    /**
     * OK
     */
    200: ServerInternalSchemasTodo;
};

export type PutApiV1TodosByIdResponse = PutApiV1TodosByIdResponses[keyof PutApiV1TodosByIdResponses];
