// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://apps` | (string & {});
};

export type Account = {
  access_token?: string;
  access_token_expires_at?: string;
  account_id?: string;
  created_at?: string;
  id?: string;
  id_token?: string;
  /**
   * for email/password auth
   */
  password?: string;
  provider_id?: string;
  refresh_token?: string;
  refresh_token_expires_at?: string;
  scope?: string;
  updated_at?: string;
  user_id?: string;
};

export type AdminUserSession = {
  session?: Session;
  state?: AdminSessionState;
};

export type CreateTodoRequest = {
  actualHours?: number;
  cost?: number;
  dueDate?: string;
  estimatedHours?: number;
  label?: 'bug' | 'feature' | 'doc';
  priority?: 'low' | 'medium' | 'high';
  progress?: number;
  status?: 'backlog' | 'todo' | 'in_progress' | 'done' | 'canceled';
  text: string;
};

export type CreateUserRequest = {
  email?: string;
  email_verified?: boolean;
  image?: string;
  metadata?: {
    [key: string]: unknown;
  };
  name?: string;
};

export type CreateUserResponse = {
  user?: User;
};

export type GetMeResponse = {
  session?: Session;
  user?: User;
};

export type GetUserByIdResponse = {
  user?: User;
};

export type HealthResponse = {
  arch?: string;
  args?: Array<string>;
  date?: string;
  memory?: {
    [key: string]: unknown;
  };
  node?: string;
  os?: string;
  status?: string;
  timezone?: string;
  timezoneName?: string;
  timezoneOffset?: number;
  uptime?: number;
  version?: string;
};

export type Session = {
  created_at?: string;
  expires_at?: string;
  id?: string;
  ip_address?: string;
  token?: string;
  updated_at?: string;
  user_agent?: string;
  user_id?: string;
};

export type SignInRequest = {
  callback_url?: string;
  email?: string;
  password?: string;
};

export type SignInResponse = {
  session?: Session;
  user?: User;
};

export type SignOutRequest = {
  session_id?: string;
  sign_out_all?: boolean;
};

export type SignOutResponse = {
  message?: string;
};

export type SignUpRequest = {
  callback_url?: string;
  email?: string;
  image?: string;
  metadata?: {
    [key: string]: unknown;
  };
  name?: string;
  password?: string;
};

export type SignUpResponse = {
  session?: Session;
  user?: User;
};

export type Todo = {
  actualHours?: number;
  completedAt?: string;
  cost?: number;
  createdAt?: string;
  dueDate?: string;
  estimatedHours?: number;
  id?: string;
  label?: string;
  priority?: TodoPriority;
  progress?: number;
  status?: TodoStatus;
  text: string;
  updatedAt?: string;
  userId?: string;
};

export type TodoPriority = 'low' | 'medium' | 'high';

export type TodoStatus =
  | 'backlog'
  | 'todo'
  | 'in_progress'
  | 'done'
  | 'canceled';

export type UpdateTodoRequest = {
  actualHours?: number;
  completedAt?: string;
  cost?: number;
  dueDate?: string;
  estimatedHours?: number;
  label?: 'bug' | 'feature' | 'doc';
  priority?: 'low' | 'medium' | 'high';
  progress?: number;
  status?: 'backlog' | 'todo' | 'in_progress' | 'done' | 'canceled';
  text?: string;
};

export type UpdateUserRequest = {
  email?: string;
  email_verified?: boolean;
  image?: string;
  metadata?: {
    [key: string]: unknown;
  };
  name?: string;
};

export type UpdateUserResponse = {
  user?: User;
};

export type User = {
  created_at?: string;
  email?: string;
  email_verified?: boolean;
  id?: string;
  image?: string;
  metadata?: {
    [key: string]: unknown;
  };
  name?: string;
  updated_at?: string;
};

export type UsersPage = {
  next_cursor?: string;
  users?: Array<User>;
};

export type AddRolePermissionRequest = {
  permission_id?: string;
};

export type AddRolePermissionResponse = {
  message?: string;
};

export type AdminSessionState = {
  created_at?: string;
  impersonation_expires_at?: string;
  impersonation_reason?: string;
  impersonator_user_id?: string;
  revoked_at?: string;
  revoked_by_user_id?: string;
  revoked_reason?: string;
  session_id?: string;
  updated_at?: string;
};

export type AdminUserState = {
  banned?: boolean;
  banned_at?: string;
  banned_by_user_id?: string;
  banned_reason?: string;
  banned_until?: string;
  created_at?: string;
  updated_at?: string;
  user_id?: string;
};

export type AssignUserRoleRequest = {
  expires_at?: string;
  role_id?: string;
};

export type AssignUserRoleResponse = {
  message?: string;
};

export type BanUserRequest = {
  banned_until?: string;
  reason?: string;
};

export type BanUserResponse = {
  state?: AdminUserState;
};

export type ChangePasswordRequest = {
  password?: string;
  token?: string;
};

export type ChangePasswordResponse = {
  message?: string;
};

export type CheckUserPermissionsRequest = {
  permission_keys?: Array<string>;
};

export type CheckUserPermissionsResponse = {
  has_permissions?: boolean;
};

export type CreateAccountRequest = {
  access_token?: string;
  access_token_expires_at?: string;
  account_id?: string;
  id_token?: string;
  password?: string;
  provider_id?: string;
  refresh_token?: string;
  refresh_token_expires_at?: string;
  scope?: string;
};

export type CreateAccountResponse = {
  account?: Account;
};

export type CreatePermissionRequest = {
  description?: string;
  is_system?: boolean;
  key?: string;
};

export type CreatePermissionResponse = {
  permission?: Permission;
};

export type CreateRoleRequest = {
  description?: string;
  is_system?: boolean;
  name?: string;
  weight?: number;
};

export type CreateRoleResponse = {
  role?: Role;
};

export type CreateSessionStateRequest = {
  impersonation_expires_at?: string;
  impersonation_reason?: string;
  impersonator_user_id?: string;
  revoke?: boolean;
  revoked_reason?: string;
};

export type CreateUserStateRequest = {
  banned?: boolean;
  banned_reason?: string;
  banned_until?: string;
};

export type DeleteAccountResponse = {
  message?: string;
};

export type DeletePermissionResponse = {
  message?: string;
};

export type DeleteRoleResponse = {
  message?: string;
};

export type DeleteSessionStateResponse = {
  message?: string;
};

export type DeleteUserResponse = {
  message?: string;
};

export type DeleteUserStateResponse = {
  message?: string;
};

export type GetAccountByIdResponse = {
  account?: Account;
};

export type GetImpersonationByIdResponse = {
  impersonation?: Impersonation;
};

export type GetSessionStateResponse = {
  state?: AdminSessionState;
};

export type GetUserPermissionsResponse = {
  permissions?: Array<UserPermissionInfo>;
};

export type GetUserStateResponse = {
  state?: AdminUserState;
};

export type Impersonation = {
  actor_session_id?: string;
  actor_user_id?: string;
  created_at?: string;
  ended_at?: string;
  ended_by_user_id?: string;
  expires_at?: string;
  id?: string;
  impersonation_session_id?: string;
  reason?: string;
  started_at?: string;
  target_user_id?: string;
  updated_at?: string;
};

export type Permission = {
  created_at?: string;
  description?: string;
  id?: string;
  is_system?: boolean;
  key?: string;
  updated_at?: string;
};

export type PermissionGrantSource = {
  granted_at?: string;
  granted_by_user_id?: string;
  role_id?: string;
  role_name?: string;
};

export type RemoveRolePermissionResponse = {
  message?: string;
};

export type RemoveUserRoleResponse = {
  message?: string;
};

export type ReplaceRolePermissionResponse = {
  message?: string;
};

export type ReplaceRolePermissionsRequest = {
  permission_ids?: Array<string>;
};

export type ReplaceUserRolesRequest = {
  role_ids?: Array<string>;
};

export type ReplaceUserRolesResponse = {
  message?: string;
};

export type RequestEmailChangeRequest = {
  callback_url?: string;
  new_email?: string;
};

export type RequestPasswordResetRequest = {
  callback_url?: string;
  email?: string;
};

export type RevokeSessionRequest = {
  reason?: string;
};

export type RevokeSessionResponse = {
  state?: AdminSessionState;
};

export type Role = {
  created_at?: string;
  description?: string;
  id?: string;
  is_system?: boolean;
  name?: string;
  updated_at?: string;
  weight?: number;
};

export type RoleDetails = {
  permissions?: Array<UserPermissionInfo>;
  role?: Role;
};

export type SendEmailVerificationRequest = {
  callback_url?: string;
};

export type StartImpersonationRequest = {
  expires_in_seconds?: number;
  reason?: string;
  target_user_id?: string;
};

export type StartImpersonationResponse = {
  impersonation?: Impersonation;
};

export type StopImpersonationResponse = {
  message?: string;
};

export type UnbanUserResponse = {
  state?: AdminUserState;
};

export type UpdateAccountRequest = {
  access_token?: string;
  access_token_expires_at?: string;
  account_id?: string;
  id_token?: string;
  password?: string;
  provider_id?: string;
  refresh_token?: string;
  refresh_token_expires_at?: string;
  scope?: string;
};

export type UpdateAccountResponse = {
  account?: Account;
};

export type UpdatePermissionRequest = {
  description?: string;
};

export type UpdatePermissionResponse = {
  permission?: Permission;
};

export type UpdateRoleRequest = {
  description?: string;
  name?: string;
  weight?: number;
};

export type UpdateRoleResponse = {
  role?: Role;
};

export type UpsertSessionStateRequest = {
  impersonation_expires_at?: string;
  impersonation_reason?: string;
  impersonator_user_id?: string;
  revoke?: boolean;
  revoked_reason?: string;
};

export type UpsertSessionStateResponse = {
  state?: AdminSessionState;
};

export type UpsertUserStateRequest = {
  banned?: boolean;
  banned_reason?: string;
  banned_until?: string;
};

export type UpsertUserStateResponse = {
  state?: AdminUserState;
};

export type UserAccountsResponse = {
  accounts?: Array<Account>;
};

export type UserPermissionInfo = {
  granted_at?: string;
  granted_by_user_id?: string;
  permission_description?: string;
  permission_id?: string;
  permission_key?: string;
  sources?: Array<PermissionGrantSource>;
};

export type UserRoleInfo = {
  assigned_at?: string;
  assigned_by_user_id?: string;
  expires_at?: string;
  role_description?: string;
  role_id?: string;
  role_name?: string;
  role_weight?: number;
};

export type GetApiV1HealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/health';
};

export type GetApiV1HealthResponses = {
  /**
   * OK
   */
  200: HealthResponse;
};

export type GetApiV1HealthResponse =
  GetApiV1HealthResponses[keyof GetApiV1HealthResponses];

export type GetApiV1TodosData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/todos';
};

export type GetApiV1TodosResponses = {
  /**
   * OK
   */
  200: Array<Todo>;
};

export type GetApiV1TodosResponse =
  GetApiV1TodosResponses[keyof GetApiV1TodosResponses];

export type PostApiV1TodosData = {
  /**
   * Todo creation request
   */
  body: CreateTodoRequest;
  path?: never;
  query?: never;
  url: '/api/v1/todos';
};

export type PostApiV1TodosErrors = {
  /**
   * Invalid request body or missing text
   */
  400: string;
};

export type PostApiV1TodosError =
  PostApiV1TodosErrors[keyof PostApiV1TodosErrors];

export type PostApiV1TodosResponses = {
  /**
   * Created
   */
  201: Todo;
};

export type PostApiV1TodosResponse =
  PostApiV1TodosResponses[keyof PostApiV1TodosResponses];

export type DeleteApiV1TodosByIdData = {
  body?: never;
  path: {
    /**
     * Todo ID
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/todos/{id}';
};

export type DeleteApiV1TodosByIdErrors = {
  /**
   * Invalid ID
   */
  400: string;
  /**
   * Todo not found
   */
  404: string;
};

export type DeleteApiV1TodosByIdError =
  DeleteApiV1TodosByIdErrors[keyof DeleteApiV1TodosByIdErrors];

export type DeleteApiV1TodosByIdResponses = {
  /**
   * No Content
   */
  204: unknown;
};

export type GetApiV1TodosByIdData = {
  body?: never;
  path: {
    /**
     * Todo ID
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/todos/{id}';
};

export type GetApiV1TodosByIdErrors = {
  /**
   * Invalid ID
   */
  400: string;
  /**
   * Todo not found
   */
  404: string;
};

export type GetApiV1TodosByIdError =
  GetApiV1TodosByIdErrors[keyof GetApiV1TodosByIdErrors];

export type GetApiV1TodosByIdResponses = {
  /**
   * OK
   */
  200: Todo;
};

export type GetApiV1TodosByIdResponse =
  GetApiV1TodosByIdResponses[keyof GetApiV1TodosByIdResponses];

export type PutApiV1TodosByIdData = {
  /**
   * Todo update request
   */
  body: UpdateTodoRequest;
  path: {
    /**
     * Todo ID
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/todos/{id}';
};

export type PutApiV1TodosByIdErrors = {
  /**
   * Invalid ID or request body
   */
  400: string;
  /**
   * Todo not found
   */
  404: string;
};

export type PutApiV1TodosByIdError =
  PutApiV1TodosByIdErrors[keyof PutApiV1TodosByIdErrors];

export type PutApiV1TodosByIdResponses = {
  /**
   * OK
   */
  200: Todo;
};

export type PutApiV1TodosByIdResponse =
  PutApiV1TodosByIdResponses[keyof PutApiV1TodosByIdResponses];

export type GetAuthAccessControlPermissionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/access-control/permissions';
};

export type GetAuthAccessControlPermissionsErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type GetAuthAccessControlPermissionsError =
  GetAuthAccessControlPermissionsErrors[keyof GetAuthAccessControlPermissionsErrors];

export type GetAuthAccessControlPermissionsResponses = {
  /**
   * OK
   */
  200: Array<Permission>;
};

export type GetAuthAccessControlPermissionsResponse =
  GetAuthAccessControlPermissionsResponses[keyof GetAuthAccessControlPermissionsResponses];

export type PostAuthAccessControlPermissionsData = {
  /**
   * Create permission request
   */
  body: CreatePermissionRequest;
  path?: never;
  query?: never;
  url: '/auth/access-control/permissions';
};

export type PostAuthAccessControlPermissionsErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthAccessControlPermissionsError =
  PostAuthAccessControlPermissionsErrors[keyof PostAuthAccessControlPermissionsErrors];

export type PostAuthAccessControlPermissionsResponses = {
  /**
   * Created
   */
  201: CreatePermissionResponse;
};

export type PostAuthAccessControlPermissionsResponse =
  PostAuthAccessControlPermissionsResponses[keyof PostAuthAccessControlPermissionsResponses];

export type DeleteAuthAccessControlPermissionsByPermissionIdData = {
  body?: never;
  path: {
    /**
     * Permission ID
     */
    permission_id: string;
  };
  query?: never;
  url: '/auth/access-control/permissions/{permission_id}';
};

export type DeleteAuthAccessControlPermissionsByPermissionIdErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type DeleteAuthAccessControlPermissionsByPermissionIdError =
  DeleteAuthAccessControlPermissionsByPermissionIdErrors[keyof DeleteAuthAccessControlPermissionsByPermissionIdErrors];

export type DeleteAuthAccessControlPermissionsByPermissionIdResponses = {
  /**
   * OK
   */
  200: DeletePermissionResponse;
};

export type DeleteAuthAccessControlPermissionsByPermissionIdResponse =
  DeleteAuthAccessControlPermissionsByPermissionIdResponses[keyof DeleteAuthAccessControlPermissionsByPermissionIdResponses];

export type GetAuthAccessControlPermissionsByPermissionIdData = {
  body?: never;
  path: {
    /**
     * Permission ID
     */
    permission_id: string;
  };
  query?: never;
  url: '/auth/access-control/permissions/{permission_id}';
};

export type GetAuthAccessControlPermissionsByPermissionIdErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type GetAuthAccessControlPermissionsByPermissionIdError =
  GetAuthAccessControlPermissionsByPermissionIdErrors[keyof GetAuthAccessControlPermissionsByPermissionIdErrors];

export type GetAuthAccessControlPermissionsByPermissionIdResponses = {
  /**
   * OK
   */
  200: Permission;
};

export type GetAuthAccessControlPermissionsByPermissionIdResponse =
  GetAuthAccessControlPermissionsByPermissionIdResponses[keyof GetAuthAccessControlPermissionsByPermissionIdResponses];

export type PatchAuthAccessControlPermissionsByPermissionIdData = {
  /**
   * Update permission request
   */
  body: UpdatePermissionRequest;
  path: {
    /**
     * Permission ID
     */
    permission_id: string;
  };
  query?: never;
  url: '/auth/access-control/permissions/{permission_id}';
};

export type PatchAuthAccessControlPermissionsByPermissionIdErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type PatchAuthAccessControlPermissionsByPermissionIdError =
  PatchAuthAccessControlPermissionsByPermissionIdErrors[keyof PatchAuthAccessControlPermissionsByPermissionIdErrors];

export type PatchAuthAccessControlPermissionsByPermissionIdResponses = {
  /**
   * OK
   */
  200: UpdatePermissionResponse;
};

export type PatchAuthAccessControlPermissionsByPermissionIdResponse =
  PatchAuthAccessControlPermissionsByPermissionIdResponses[keyof PatchAuthAccessControlPermissionsByPermissionIdResponses];

export type GetAuthAccessControlRolesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/access-control/roles';
};

export type GetAuthAccessControlRolesErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type GetAuthAccessControlRolesError =
  GetAuthAccessControlRolesErrors[keyof GetAuthAccessControlRolesErrors];

export type GetAuthAccessControlRolesResponses = {
  /**
   * OK
   */
  200: Array<Role>;
};

export type GetAuthAccessControlRolesResponse =
  GetAuthAccessControlRolesResponses[keyof GetAuthAccessControlRolesResponses];

export type PostAuthAccessControlRolesData = {
  /**
   * Create role request
   */
  body: CreateRoleRequest;
  path?: never;
  query?: never;
  url: '/auth/access-control/roles';
};

export type PostAuthAccessControlRolesErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthAccessControlRolesError =
  PostAuthAccessControlRolesErrors[keyof PostAuthAccessControlRolesErrors];

export type PostAuthAccessControlRolesResponses = {
  /**
   * Created
   */
  201: CreateRoleResponse;
};

export type PostAuthAccessControlRolesResponse =
  PostAuthAccessControlRolesResponses[keyof PostAuthAccessControlRolesResponses];

export type GetAuthAccessControlRolesByNameByRoleNameData = {
  body?: never;
  path: {
    /**
     * Role name
     */
    role_name: string;
  };
  query?: never;
  url: '/auth/access-control/roles/by-name/{role_name}';
};

export type GetAuthAccessControlRolesByNameByRoleNameErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type GetAuthAccessControlRolesByNameByRoleNameError =
  GetAuthAccessControlRolesByNameByRoleNameErrors[keyof GetAuthAccessControlRolesByNameByRoleNameErrors];

export type GetAuthAccessControlRolesByNameByRoleNameResponses = {
  /**
   * OK
   */
  200: Role;
};

export type GetAuthAccessControlRolesByNameByRoleNameResponse =
  GetAuthAccessControlRolesByNameByRoleNameResponses[keyof GetAuthAccessControlRolesByNameByRoleNameResponses];

export type DeleteAuthAccessControlRolesByRoleIdData = {
  body?: never;
  path: {
    /**
     * Role ID
     */
    role_id: string;
  };
  query?: never;
  url: '/auth/access-control/roles/{role_id}';
};

export type DeleteAuthAccessControlRolesByRoleIdErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type DeleteAuthAccessControlRolesByRoleIdError =
  DeleteAuthAccessControlRolesByRoleIdErrors[keyof DeleteAuthAccessControlRolesByRoleIdErrors];

export type DeleteAuthAccessControlRolesByRoleIdResponses = {
  /**
   * OK
   */
  200: DeleteRoleResponse;
};

export type DeleteAuthAccessControlRolesByRoleIdResponse =
  DeleteAuthAccessControlRolesByRoleIdResponses[keyof DeleteAuthAccessControlRolesByRoleIdResponses];

export type GetAuthAccessControlRolesByRoleIdData = {
  body?: never;
  path: {
    /**
     * Role ID
     */
    role_id: string;
  };
  query?: never;
  url: '/auth/access-control/roles/{role_id}';
};

export type GetAuthAccessControlRolesByRoleIdErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type GetAuthAccessControlRolesByRoleIdError =
  GetAuthAccessControlRolesByRoleIdErrors[keyof GetAuthAccessControlRolesByRoleIdErrors];

export type GetAuthAccessControlRolesByRoleIdResponses = {
  /**
   * OK
   */
  200: RoleDetails;
};

export type GetAuthAccessControlRolesByRoleIdResponse =
  GetAuthAccessControlRolesByRoleIdResponses[keyof GetAuthAccessControlRolesByRoleIdResponses];

export type PatchAuthAccessControlRolesByRoleIdData = {
  /**
   * Update role request
   */
  body: UpdateRoleRequest;
  path: {
    /**
     * Role ID
     */
    role_id: string;
  };
  query?: never;
  url: '/auth/access-control/roles/{role_id}';
};

export type PatchAuthAccessControlRolesByRoleIdErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type PatchAuthAccessControlRolesByRoleIdError =
  PatchAuthAccessControlRolesByRoleIdErrors[keyof PatchAuthAccessControlRolesByRoleIdErrors];

export type PatchAuthAccessControlRolesByRoleIdResponses = {
  /**
   * OK
   */
  200: UpdateRoleResponse;
};

export type PatchAuthAccessControlRolesByRoleIdResponse =
  PatchAuthAccessControlRolesByRoleIdResponses[keyof PatchAuthAccessControlRolesByRoleIdResponses];

export type GetAuthAccessControlRolesByRoleIdPermissionsData = {
  body?: never;
  path: {
    /**
     * Role ID
     */
    role_id: string;
  };
  query?: never;
  url: '/auth/access-control/roles/{role_id}/permissions';
};

export type GetAuthAccessControlRolesByRoleIdPermissionsErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type GetAuthAccessControlRolesByRoleIdPermissionsError =
  GetAuthAccessControlRolesByRoleIdPermissionsErrors[keyof GetAuthAccessControlRolesByRoleIdPermissionsErrors];

export type GetAuthAccessControlRolesByRoleIdPermissionsResponses = {
  /**
   * OK
   */
  200: Array<Permission>;
};

export type GetAuthAccessControlRolesByRoleIdPermissionsResponse =
  GetAuthAccessControlRolesByRoleIdPermissionsResponses[keyof GetAuthAccessControlRolesByRoleIdPermissionsResponses];

export type PostAuthAccessControlRolesByRoleIdPermissionsData = {
  /**
   * Add role permission request
   */
  body: AddRolePermissionRequest;
  path: {
    /**
     * Role ID
     */
    role_id: string;
  };
  query?: never;
  url: '/auth/access-control/roles/{role_id}/permissions';
};

export type PostAuthAccessControlRolesByRoleIdPermissionsErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthAccessControlRolesByRoleIdPermissionsError =
  PostAuthAccessControlRolesByRoleIdPermissionsErrors[keyof PostAuthAccessControlRolesByRoleIdPermissionsErrors];

export type PostAuthAccessControlRolesByRoleIdPermissionsResponses = {
  /**
   * OK
   */
  200: AddRolePermissionResponse;
};

export type PostAuthAccessControlRolesByRoleIdPermissionsResponse =
  PostAuthAccessControlRolesByRoleIdPermissionsResponses[keyof PostAuthAccessControlRolesByRoleIdPermissionsResponses];

export type PutAuthAccessControlRolesByRoleIdPermissionsData = {
  /**
   * Replace role permissions request
   */
  body: ReplaceRolePermissionsRequest;
  path: {
    /**
     * Role ID
     */
    role_id: string;
  };
  query?: never;
  url: '/auth/access-control/roles/{role_id}/permissions';
};

export type PutAuthAccessControlRolesByRoleIdPermissionsErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PutAuthAccessControlRolesByRoleIdPermissionsError =
  PutAuthAccessControlRolesByRoleIdPermissionsErrors[keyof PutAuthAccessControlRolesByRoleIdPermissionsErrors];

export type PutAuthAccessControlRolesByRoleIdPermissionsResponses = {
  /**
   * OK
   */
  200: ReplaceRolePermissionResponse;
};

export type PutAuthAccessControlRolesByRoleIdPermissionsResponse =
  PutAuthAccessControlRolesByRoleIdPermissionsResponses[keyof PutAuthAccessControlRolesByRoleIdPermissionsResponses];

export type DeleteAuthAccessControlRolesByRoleIdPermissionsByPermissionIdData =
  {
    body?: never;
    path: {
      /**
       * Role ID
       */
      role_id: string;
      /**
       * Permission ID
       */
      permission_id: string;
    };
    query?: never;
    url: '/auth/access-control/roles/{role_id}/permissions/{permission_id}';
  };

export type DeleteAuthAccessControlRolesByRoleIdPermissionsByPermissionIdErrors =
  {
    /**
     * Unauthorized
     */
    401: string;
  };

export type DeleteAuthAccessControlRolesByRoleIdPermissionsByPermissionIdError =
  DeleteAuthAccessControlRolesByRoleIdPermissionsByPermissionIdErrors[keyof DeleteAuthAccessControlRolesByRoleIdPermissionsByPermissionIdErrors];

export type DeleteAuthAccessControlRolesByRoleIdPermissionsByPermissionIdResponses =
  {
    /**
     * OK
     */
    200: RemoveRolePermissionResponse;
  };

export type DeleteAuthAccessControlRolesByRoleIdPermissionsByPermissionIdResponse =
  DeleteAuthAccessControlRolesByRoleIdPermissionsByPermissionIdResponses[keyof DeleteAuthAccessControlRolesByRoleIdPermissionsByPermissionIdResponses];

export type GetAuthAccessControlUsersByUserIdPermissionsData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/access-control/users/{user_id}/permissions';
};

export type GetAuthAccessControlUsersByUserIdPermissionsErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type GetAuthAccessControlUsersByUserIdPermissionsError =
  GetAuthAccessControlUsersByUserIdPermissionsErrors[keyof GetAuthAccessControlUsersByUserIdPermissionsErrors];

export type GetAuthAccessControlUsersByUserIdPermissionsResponses = {
  /**
   * OK
   */
  200: GetUserPermissionsResponse;
};

export type GetAuthAccessControlUsersByUserIdPermissionsResponse =
  GetAuthAccessControlUsersByUserIdPermissionsResponses[keyof GetAuthAccessControlUsersByUserIdPermissionsResponses];

export type PostAuthAccessControlUsersByUserIdPermissionsCheckData = {
  /**
   * Check user permissions request
   */
  body: CheckUserPermissionsRequest;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/access-control/users/{user_id}/permissions/check';
};

export type PostAuthAccessControlUsersByUserIdPermissionsCheckErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthAccessControlUsersByUserIdPermissionsCheckError =
  PostAuthAccessControlUsersByUserIdPermissionsCheckErrors[keyof PostAuthAccessControlUsersByUserIdPermissionsCheckErrors];

export type PostAuthAccessControlUsersByUserIdPermissionsCheckResponses = {
  /**
   * OK
   */
  200: CheckUserPermissionsResponse;
};

export type PostAuthAccessControlUsersByUserIdPermissionsCheckResponse =
  PostAuthAccessControlUsersByUserIdPermissionsCheckResponses[keyof PostAuthAccessControlUsersByUserIdPermissionsCheckResponses];

export type GetAuthAccessControlUsersByUserIdRolesData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/access-control/users/{user_id}/roles';
};

export type GetAuthAccessControlUsersByUserIdRolesErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type GetAuthAccessControlUsersByUserIdRolesError =
  GetAuthAccessControlUsersByUserIdRolesErrors[keyof GetAuthAccessControlUsersByUserIdRolesErrors];

export type GetAuthAccessControlUsersByUserIdRolesResponses = {
  /**
   * OK
   */
  200: Array<UserRoleInfo>;
};

export type GetAuthAccessControlUsersByUserIdRolesResponse =
  GetAuthAccessControlUsersByUserIdRolesResponses[keyof GetAuthAccessControlUsersByUserIdRolesResponses];

export type PostAuthAccessControlUsersByUserIdRolesData = {
  /**
   * Assign user role request
   */
  body: AssignUserRoleRequest;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/access-control/users/{user_id}/roles';
};

export type PostAuthAccessControlUsersByUserIdRolesErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthAccessControlUsersByUserIdRolesError =
  PostAuthAccessControlUsersByUserIdRolesErrors[keyof PostAuthAccessControlUsersByUserIdRolesErrors];

export type PostAuthAccessControlUsersByUserIdRolesResponses = {
  /**
   * OK
   */
  200: AssignUserRoleResponse;
};

export type PostAuthAccessControlUsersByUserIdRolesResponse =
  PostAuthAccessControlUsersByUserIdRolesResponses[keyof PostAuthAccessControlUsersByUserIdRolesResponses];

export type PutAuthAccessControlUsersByUserIdRolesData = {
  /**
   * Replace user roles request
   */
  body: ReplaceUserRolesRequest;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/access-control/users/{user_id}/roles';
};

export type PutAuthAccessControlUsersByUserIdRolesErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PutAuthAccessControlUsersByUserIdRolesError =
  PutAuthAccessControlUsersByUserIdRolesErrors[keyof PutAuthAccessControlUsersByUserIdRolesErrors];

export type PutAuthAccessControlUsersByUserIdRolesResponses = {
  /**
   * OK
   */
  200: ReplaceUserRolesResponse;
};

export type PutAuthAccessControlUsersByUserIdRolesResponse =
  PutAuthAccessControlUsersByUserIdRolesResponses[keyof PutAuthAccessControlUsersByUserIdRolesResponses];

export type DeleteAuthAccessControlUsersByUserIdRolesByRoleIdData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    user_id: string;
    /**
     * Role ID
     */
    role_id: string;
  };
  query?: never;
  url: '/auth/access-control/users/{user_id}/roles/{role_id}';
};

export type DeleteAuthAccessControlUsersByUserIdRolesByRoleIdErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type DeleteAuthAccessControlUsersByUserIdRolesByRoleIdError =
  DeleteAuthAccessControlUsersByUserIdRolesByRoleIdErrors[keyof DeleteAuthAccessControlUsersByUserIdRolesByRoleIdErrors];

export type DeleteAuthAccessControlUsersByUserIdRolesByRoleIdResponses = {
  /**
   * OK
   */
  200: RemoveUserRoleResponse;
};

export type DeleteAuthAccessControlUsersByUserIdRolesByRoleIdResponse =
  DeleteAuthAccessControlUsersByUserIdRolesByRoleIdResponses[keyof DeleteAuthAccessControlUsersByUserIdRolesByRoleIdResponses];

export type DeleteAuthAdminAccountsByIdData = {
  body?: never;
  path: {
    /**
     * Account ID
     */
    id: string;
  };
  query?: never;
  url: '/auth/admin/accounts/{id}';
};

export type DeleteAuthAdminAccountsByIdErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type DeleteAuthAdminAccountsByIdError =
  DeleteAuthAdminAccountsByIdErrors[keyof DeleteAuthAdminAccountsByIdErrors];

export type DeleteAuthAdminAccountsByIdResponses = {
  /**
   * OK
   */
  200: DeleteAccountResponse;
};

export type DeleteAuthAdminAccountsByIdResponse =
  DeleteAuthAdminAccountsByIdResponses[keyof DeleteAuthAdminAccountsByIdResponses];

export type GetAuthAdminAccountsByIdData = {
  body?: never;
  path: {
    /**
     * Account ID
     */
    id: string;
  };
  query?: never;
  url: '/auth/admin/accounts/{id}';
};

export type GetAuthAdminAccountsByIdErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type GetAuthAdminAccountsByIdError =
  GetAuthAdminAccountsByIdErrors[keyof GetAuthAdminAccountsByIdErrors];

export type GetAuthAdminAccountsByIdResponses = {
  /**
   * OK
   */
  200: GetAccountByIdResponse;
};

export type GetAuthAdminAccountsByIdResponse =
  GetAuthAdminAccountsByIdResponses[keyof GetAuthAdminAccountsByIdResponses];

export type PatchAuthAdminAccountsByIdData = {
  /**
   * Update account request
   */
  body: UpdateAccountRequest;
  path: {
    /**
     * Account ID
     */
    id: string;
  };
  query?: never;
  url: '/auth/admin/accounts/{id}';
};

export type PatchAuthAdminAccountsByIdErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type PatchAuthAdminAccountsByIdError =
  PatchAuthAdminAccountsByIdErrors[keyof PatchAuthAdminAccountsByIdErrors];

export type PatchAuthAdminAccountsByIdResponses = {
  /**
   * OK
   */
  200: UpdateAccountResponse;
};

export type PatchAuthAdminAccountsByIdResponse =
  PatchAuthAdminAccountsByIdResponses[keyof PatchAuthAdminAccountsByIdResponses];

export type GetAuthAdminImpersonationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/admin/impersonations';
};

export type GetAuthAdminImpersonationsErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type GetAuthAdminImpersonationsError =
  GetAuthAdminImpersonationsErrors[keyof GetAuthAdminImpersonationsErrors];

export type GetAuthAdminImpersonationsResponses = {
  /**
   * OK
   */
  200: Array<Impersonation>;
};

export type GetAuthAdminImpersonationsResponse =
  GetAuthAdminImpersonationsResponses[keyof GetAuthAdminImpersonationsResponses];

export type PostAuthAdminImpersonationsData = {
  /**
   * Start impersonation request
   */
  body: StartImpersonationRequest;
  path?: never;
  query?: never;
  url: '/auth/admin/impersonations';
};

export type PostAuthAdminImpersonationsErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthAdminImpersonationsError =
  PostAuthAdminImpersonationsErrors[keyof PostAuthAdminImpersonationsErrors];

export type PostAuthAdminImpersonationsResponses = {
  /**
   * Created
   */
  201: StartImpersonationResponse;
};

export type PostAuthAdminImpersonationsResponse =
  PostAuthAdminImpersonationsResponses[keyof PostAuthAdminImpersonationsResponses];

export type GetAuthAdminImpersonationsByImpersonationIdData = {
  body?: never;
  path: {
    /**
     * Impersonation ID
     */
    impersonation_id: string;
  };
  query?: never;
  url: '/auth/admin/impersonations/{impersonation_id}';
};

export type GetAuthAdminImpersonationsByImpersonationIdErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type GetAuthAdminImpersonationsByImpersonationIdError =
  GetAuthAdminImpersonationsByImpersonationIdErrors[keyof GetAuthAdminImpersonationsByImpersonationIdErrors];

export type GetAuthAdminImpersonationsByImpersonationIdResponses = {
  /**
   * OK
   */
  200: GetImpersonationByIdResponse;
};

export type GetAuthAdminImpersonationsByImpersonationIdResponse =
  GetAuthAdminImpersonationsByImpersonationIdResponses[keyof GetAuthAdminImpersonationsByImpersonationIdResponses];

export type PostAuthAdminImpersonationsByImpersonationIdStopData = {
  body?: never;
  path: {
    /**
     * Impersonation ID
     */
    impersonation_id: string;
  };
  query?: never;
  url: '/auth/admin/impersonations/{impersonation_id}/stop';
};

export type PostAuthAdminImpersonationsByImpersonationIdStopErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type PostAuthAdminImpersonationsByImpersonationIdStopError =
  PostAuthAdminImpersonationsByImpersonationIdStopErrors[keyof PostAuthAdminImpersonationsByImpersonationIdStopErrors];

export type PostAuthAdminImpersonationsByImpersonationIdStopResponses = {
  /**
   * OK
   */
  200: StopImpersonationResponse;
};

export type PostAuthAdminImpersonationsByImpersonationIdStopResponse =
  PostAuthAdminImpersonationsByImpersonationIdStopResponses[keyof PostAuthAdminImpersonationsByImpersonationIdStopResponses];

export type GetAuthAdminSessionsStatesRevokedData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/admin/sessions/states/revoked';
};

export type GetAuthAdminSessionsStatesRevokedErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type GetAuthAdminSessionsStatesRevokedError =
  GetAuthAdminSessionsStatesRevokedErrors[keyof GetAuthAdminSessionsStatesRevokedErrors];

export type GetAuthAdminSessionsStatesRevokedResponses = {
  /**
   * OK
   */
  200: Array<AdminSessionState>;
};

export type GetAuthAdminSessionsStatesRevokedResponse =
  GetAuthAdminSessionsStatesRevokedResponses[keyof GetAuthAdminSessionsStatesRevokedResponses];

export type PostAuthAdminSessionsBySessionIdRevokeData = {
  /**
   * Revoke session request
   */
  body: RevokeSessionRequest;
  path: {
    /**
     * Session ID
     */
    session_id: string;
  };
  query?: never;
  url: '/auth/admin/sessions/{session_id}/revoke';
};

export type PostAuthAdminSessionsBySessionIdRevokeErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthAdminSessionsBySessionIdRevokeError =
  PostAuthAdminSessionsBySessionIdRevokeErrors[keyof PostAuthAdminSessionsBySessionIdRevokeErrors];

export type PostAuthAdminSessionsBySessionIdRevokeResponses = {
  /**
   * OK
   */
  200: RevokeSessionResponse;
};

export type PostAuthAdminSessionsBySessionIdRevokeResponse =
  PostAuthAdminSessionsBySessionIdRevokeResponses[keyof PostAuthAdminSessionsBySessionIdRevokeResponses];

export type DeleteAuthAdminSessionsBySessionIdStateData = {
  body?: never;
  path: {
    /**
     * Session ID
     */
    session_id: string;
  };
  query?: never;
  url: '/auth/admin/sessions/{session_id}/state';
};

export type DeleteAuthAdminSessionsBySessionIdStateErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type DeleteAuthAdminSessionsBySessionIdStateError =
  DeleteAuthAdminSessionsBySessionIdStateErrors[keyof DeleteAuthAdminSessionsBySessionIdStateErrors];

export type DeleteAuthAdminSessionsBySessionIdStateResponses = {
  /**
   * OK
   */
  200: DeleteSessionStateResponse;
};

export type DeleteAuthAdminSessionsBySessionIdStateResponse =
  DeleteAuthAdminSessionsBySessionIdStateResponses[keyof DeleteAuthAdminSessionsBySessionIdStateResponses];

export type GetAuthAdminSessionsBySessionIdStateData = {
  body?: never;
  path: {
    /**
     * Session ID
     */
    session_id: string;
  };
  query?: never;
  url: '/auth/admin/sessions/{session_id}/state';
};

export type GetAuthAdminSessionsBySessionIdStateErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type GetAuthAdminSessionsBySessionIdStateError =
  GetAuthAdminSessionsBySessionIdStateErrors[keyof GetAuthAdminSessionsBySessionIdStateErrors];

export type GetAuthAdminSessionsBySessionIdStateResponses = {
  /**
   * OK
   */
  200: GetSessionStateResponse;
};

export type GetAuthAdminSessionsBySessionIdStateResponse =
  GetAuthAdminSessionsBySessionIdStateResponses[keyof GetAuthAdminSessionsBySessionIdStateResponses];

export type PatchAuthAdminSessionsBySessionIdStateData = {
  /**
   * Update session state request
   */
  body: UpsertSessionStateRequest;
  path: {
    /**
     * Session ID
     */
    session_id: string;
  };
  query?: never;
  url: '/auth/admin/sessions/{session_id}/state';
};

export type PatchAuthAdminSessionsBySessionIdStateErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PatchAuthAdminSessionsBySessionIdStateError =
  PatchAuthAdminSessionsBySessionIdStateErrors[keyof PatchAuthAdminSessionsBySessionIdStateErrors];

export type PatchAuthAdminSessionsBySessionIdStateResponses = {
  /**
   * OK
   */
  200: UpsertSessionStateResponse;
};

export type PatchAuthAdminSessionsBySessionIdStateResponse =
  PatchAuthAdminSessionsBySessionIdStateResponses[keyof PatchAuthAdminSessionsBySessionIdStateResponses];

export type PostAuthAdminSessionsBySessionIdStateData = {
  /**
   * Create session state request
   */
  body: CreateSessionStateRequest;
  path: {
    /**
     * Session ID
     */
    session_id: string;
  };
  query?: never;
  url: '/auth/admin/sessions/{session_id}/state';
};

export type PostAuthAdminSessionsBySessionIdStateErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthAdminSessionsBySessionIdStateError =
  PostAuthAdminSessionsBySessionIdStateErrors[keyof PostAuthAdminSessionsBySessionIdStateErrors];

export type PostAuthAdminSessionsBySessionIdStateResponses = {
  /**
   * Created
   */
  201: UpsertSessionStateResponse;
};

export type PostAuthAdminSessionsBySessionIdStateResponse =
  PostAuthAdminSessionsBySessionIdStateResponses[keyof PostAuthAdminSessionsBySessionIdStateResponses];

export type GetAuthAdminUsersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Pagination cursor
     */
    cursor?: string;
    /**
     * Pagination limit
     */
    limit?: number;
  };
  url: '/auth/admin/users';
};

export type GetAuthAdminUsersErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type GetAuthAdminUsersError =
  GetAuthAdminUsersErrors[keyof GetAuthAdminUsersErrors];

export type GetAuthAdminUsersResponses = {
  /**
   * OK
   */
  200: UsersPage;
};

export type GetAuthAdminUsersResponse =
  GetAuthAdminUsersResponses[keyof GetAuthAdminUsersResponses];

export type PostAuthAdminUsersData = {
  /**
   * Create user request
   */
  body: CreateUserRequest;
  path?: never;
  query?: never;
  url: '/auth/admin/users';
};

export type PostAuthAdminUsersErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthAdminUsersError =
  PostAuthAdminUsersErrors[keyof PostAuthAdminUsersErrors];

export type PostAuthAdminUsersResponses = {
  /**
   * Created
   */
  201: CreateUserResponse;
};

export type PostAuthAdminUsersResponse =
  PostAuthAdminUsersResponses[keyof PostAuthAdminUsersResponses];

export type GetAuthAdminUsersStatesBannedData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/admin/users/states/banned';
};

export type GetAuthAdminUsersStatesBannedErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type GetAuthAdminUsersStatesBannedError =
  GetAuthAdminUsersStatesBannedErrors[keyof GetAuthAdminUsersStatesBannedErrors];

export type GetAuthAdminUsersStatesBannedResponses = {
  /**
   * OK
   */
  200: Array<AdminUserState>;
};

export type GetAuthAdminUsersStatesBannedResponse =
  GetAuthAdminUsersStatesBannedResponses[keyof GetAuthAdminUsersStatesBannedResponses];

export type DeleteAuthAdminUsersByUserIdData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/admin/users/{user_id}';
};

export type DeleteAuthAdminUsersByUserIdErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type DeleteAuthAdminUsersByUserIdError =
  DeleteAuthAdminUsersByUserIdErrors[keyof DeleteAuthAdminUsersByUserIdErrors];

export type DeleteAuthAdminUsersByUserIdResponses = {
  /**
   * OK
   */
  200: DeleteUserResponse;
};

export type DeleteAuthAdminUsersByUserIdResponse =
  DeleteAuthAdminUsersByUserIdResponses[keyof DeleteAuthAdminUsersByUserIdResponses];

export type GetAuthAdminUsersByUserIdData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/admin/users/{user_id}';
};

export type GetAuthAdminUsersByUserIdErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type GetAuthAdminUsersByUserIdError =
  GetAuthAdminUsersByUserIdErrors[keyof GetAuthAdminUsersByUserIdErrors];

export type GetAuthAdminUsersByUserIdResponses = {
  /**
   * OK
   */
  200: GetUserByIdResponse;
};

export type GetAuthAdminUsersByUserIdResponse =
  GetAuthAdminUsersByUserIdResponses[keyof GetAuthAdminUsersByUserIdResponses];

export type PatchAuthAdminUsersByUserIdData = {
  /**
   * Update user request
   */
  body: UpdateUserRequest;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/admin/users/{user_id}';
};

export type PatchAuthAdminUsersByUserIdErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type PatchAuthAdminUsersByUserIdError =
  PatchAuthAdminUsersByUserIdErrors[keyof PatchAuthAdminUsersByUserIdErrors];

export type PatchAuthAdminUsersByUserIdResponses = {
  /**
   * OK
   */
  200: UpdateUserResponse;
};

export type PatchAuthAdminUsersByUserIdResponse =
  PatchAuthAdminUsersByUserIdResponses[keyof PatchAuthAdminUsersByUserIdResponses];

export type GetAuthAdminUsersByUserIdAccountsData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/admin/users/{user_id}/accounts';
};

export type GetAuthAdminUsersByUserIdAccountsErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type GetAuthAdminUsersByUserIdAccountsError =
  GetAuthAdminUsersByUserIdAccountsErrors[keyof GetAuthAdminUsersByUserIdAccountsErrors];

export type GetAuthAdminUsersByUserIdAccountsResponses = {
  /**
   * OK
   */
  200: UserAccountsResponse;
};

export type GetAuthAdminUsersByUserIdAccountsResponse =
  GetAuthAdminUsersByUserIdAccountsResponses[keyof GetAuthAdminUsersByUserIdAccountsResponses];

export type PostAuthAdminUsersByUserIdAccountsData = {
  /**
   * Create account request
   */
  body: CreateAccountRequest;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/admin/users/{user_id}/accounts';
};

export type PostAuthAdminUsersByUserIdAccountsErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthAdminUsersByUserIdAccountsError =
  PostAuthAdminUsersByUserIdAccountsErrors[keyof PostAuthAdminUsersByUserIdAccountsErrors];

export type PostAuthAdminUsersByUserIdAccountsResponses = {
  /**
   * Created
   */
  201: CreateAccountResponse;
};

export type PostAuthAdminUsersByUserIdAccountsResponse =
  PostAuthAdminUsersByUserIdAccountsResponses[keyof PostAuthAdminUsersByUserIdAccountsResponses];

export type PostAuthAdminUsersByUserIdBanData = {
  /**
   * Ban user request
   */
  body: BanUserRequest;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/admin/users/{user_id}/ban';
};

export type PostAuthAdminUsersByUserIdBanErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthAdminUsersByUserIdBanError =
  PostAuthAdminUsersByUserIdBanErrors[keyof PostAuthAdminUsersByUserIdBanErrors];

export type PostAuthAdminUsersByUserIdBanResponses = {
  /**
   * OK
   */
  200: BanUserResponse;
};

export type PostAuthAdminUsersByUserIdBanResponse =
  PostAuthAdminUsersByUserIdBanResponses[keyof PostAuthAdminUsersByUserIdBanResponses];

export type GetAuthAdminUsersByUserIdSessionsData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/admin/users/{user_id}/sessions';
};

export type GetAuthAdminUsersByUserIdSessionsErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type GetAuthAdminUsersByUserIdSessionsError =
  GetAuthAdminUsersByUserIdSessionsErrors[keyof GetAuthAdminUsersByUserIdSessionsErrors];

export type GetAuthAdminUsersByUserIdSessionsResponses = {
  /**
   * OK
   */
  200: Array<AdminUserSession>;
};

export type GetAuthAdminUsersByUserIdSessionsResponse =
  GetAuthAdminUsersByUserIdSessionsResponses[keyof GetAuthAdminUsersByUserIdSessionsResponses];

export type DeleteAuthAdminUsersByUserIdStateData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/admin/users/{user_id}/state';
};

export type DeleteAuthAdminUsersByUserIdStateErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type DeleteAuthAdminUsersByUserIdStateError =
  DeleteAuthAdminUsersByUserIdStateErrors[keyof DeleteAuthAdminUsersByUserIdStateErrors];

export type DeleteAuthAdminUsersByUserIdStateResponses = {
  /**
   * OK
   */
  200: DeleteUserStateResponse;
};

export type DeleteAuthAdminUsersByUserIdStateResponse =
  DeleteAuthAdminUsersByUserIdStateResponses[keyof DeleteAuthAdminUsersByUserIdStateResponses];

export type GetAuthAdminUsersByUserIdStateData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/admin/users/{user_id}/state';
};

export type GetAuthAdminUsersByUserIdStateErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type GetAuthAdminUsersByUserIdStateError =
  GetAuthAdminUsersByUserIdStateErrors[keyof GetAuthAdminUsersByUserIdStateErrors];

export type GetAuthAdminUsersByUserIdStateResponses = {
  /**
   * OK
   */
  200: GetUserStateResponse;
};

export type GetAuthAdminUsersByUserIdStateResponse =
  GetAuthAdminUsersByUserIdStateResponses[keyof GetAuthAdminUsersByUserIdStateResponses];

export type PatchAuthAdminUsersByUserIdStateData = {
  /**
   * Update user state request
   */
  body: UpsertUserStateRequest;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/admin/users/{user_id}/state';
};

export type PatchAuthAdminUsersByUserIdStateErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PatchAuthAdminUsersByUserIdStateError =
  PatchAuthAdminUsersByUserIdStateErrors[keyof PatchAuthAdminUsersByUserIdStateErrors];

export type PatchAuthAdminUsersByUserIdStateResponses = {
  /**
   * OK
   */
  200: UpsertUserStateResponse;
};

export type PatchAuthAdminUsersByUserIdStateResponse =
  PatchAuthAdminUsersByUserIdStateResponses[keyof PatchAuthAdminUsersByUserIdStateResponses];

export type PostAuthAdminUsersByUserIdStateData = {
  /**
   * Create user state request
   */
  body: CreateUserStateRequest;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/admin/users/{user_id}/state';
};

export type PostAuthAdminUsersByUserIdStateErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthAdminUsersByUserIdStateError =
  PostAuthAdminUsersByUserIdStateErrors[keyof PostAuthAdminUsersByUserIdStateErrors];

export type PostAuthAdminUsersByUserIdStateResponses = {
  /**
   * Created
   */
  201: UpsertUserStateResponse;
};

export type PostAuthAdminUsersByUserIdStateResponse =
  PostAuthAdminUsersByUserIdStateResponses[keyof PostAuthAdminUsersByUserIdStateResponses];

export type PostAuthAdminUsersByUserIdUnbanData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    user_id: string;
  };
  query?: never;
  url: '/auth/admin/users/{user_id}/unban';
};

export type PostAuthAdminUsersByUserIdUnbanErrors = {
  /**
   * Unauthorized
   */
  401: string;
  /**
   * Not found
   */
  404: string;
};

export type PostAuthAdminUsersByUserIdUnbanError =
  PostAuthAdminUsersByUserIdUnbanErrors[keyof PostAuthAdminUsersByUserIdUnbanErrors];

export type PostAuthAdminUsersByUserIdUnbanResponses = {
  /**
   * OK
   */
  200: UnbanUserResponse;
};

export type PostAuthAdminUsersByUserIdUnbanResponse =
  PostAuthAdminUsersByUserIdUnbanResponses[keyof PostAuthAdminUsersByUserIdUnbanResponses];

export type PostAuthEmailPasswordChangePasswordData = {
  /**
   * Change password request
   */
  body: ChangePasswordRequest;
  path?: never;
  query?: never;
  url: '/auth/email-password/change-password';
};

export type PostAuthEmailPasswordChangePasswordErrors = {
  /**
   * Bad request
   */
  400: string;
};

export type PostAuthEmailPasswordChangePasswordError =
  PostAuthEmailPasswordChangePasswordErrors[keyof PostAuthEmailPasswordChangePasswordErrors];

export type PostAuthEmailPasswordChangePasswordResponses = {
  /**
   * OK
   */
  200: ChangePasswordResponse;
};

export type PostAuthEmailPasswordChangePasswordResponse =
  PostAuthEmailPasswordChangePasswordResponses[keyof PostAuthEmailPasswordChangePasswordResponses];

export type PostAuthEmailPasswordRequestEmailChangeData = {
  /**
   * Request email change request
   */
  body: RequestEmailChangeRequest;
  path?: never;
  query?: never;
  url: '/auth/email-password/request-email-change';
};

export type PostAuthEmailPasswordRequestEmailChangeErrors = {
  /**
   * Bad request
   */
  400: string;
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthEmailPasswordRequestEmailChangeError =
  PostAuthEmailPasswordRequestEmailChangeErrors[keyof PostAuthEmailPasswordRequestEmailChangeErrors];

export type PostAuthEmailPasswordRequestEmailChangeResponses = {
  /**
   * Email change requested
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostAuthEmailPasswordRequestEmailChangeResponse =
  PostAuthEmailPasswordRequestEmailChangeResponses[keyof PostAuthEmailPasswordRequestEmailChangeResponses];

export type PostAuthEmailPasswordRequestPasswordResetData = {
  /**
   * Request password reset request
   */
  body: RequestPasswordResetRequest;
  path?: never;
  query?: never;
  url: '/auth/email-password/request-password-reset';
};

export type PostAuthEmailPasswordRequestPasswordResetErrors = {
  /**
   * Bad request
   */
  400: string;
};

export type PostAuthEmailPasswordRequestPasswordResetError =
  PostAuthEmailPasswordRequestPasswordResetErrors[keyof PostAuthEmailPasswordRequestPasswordResetErrors];

export type PostAuthEmailPasswordRequestPasswordResetResponses = {
  /**
   * Password reset requested
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostAuthEmailPasswordRequestPasswordResetResponse =
  PostAuthEmailPasswordRequestPasswordResetResponses[keyof PostAuthEmailPasswordRequestPasswordResetResponses];

export type PostAuthEmailPasswordSendEmailVerificationData = {
  /**
   * Send email verification request
   */
  body: SendEmailVerificationRequest;
  path?: never;
  query?: never;
  url: '/auth/email-password/send-email-verification';
};

export type PostAuthEmailPasswordSendEmailVerificationErrors = {
  /**
   * Bad request
   */
  400: string;
};

export type PostAuthEmailPasswordSendEmailVerificationError =
  PostAuthEmailPasswordSendEmailVerificationErrors[keyof PostAuthEmailPasswordSendEmailVerificationErrors];

export type PostAuthEmailPasswordSendEmailVerificationResponses = {
  /**
   * Email verification sent
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostAuthEmailPasswordSendEmailVerificationResponse =
  PostAuthEmailPasswordSendEmailVerificationResponses[keyof PostAuthEmailPasswordSendEmailVerificationResponses];

export type PostAuthEmailPasswordSignInData = {
  /**
   * Sign in request
   */
  body: SignInRequest;
  path?: never;
  query?: never;
  url: '/auth/email-password/sign-in';
};

export type PostAuthEmailPasswordSignInErrors = {
  /**
   * Bad request
   */
  400: string;
};

export type PostAuthEmailPasswordSignInError =
  PostAuthEmailPasswordSignInErrors[keyof PostAuthEmailPasswordSignInErrors];

export type PostAuthEmailPasswordSignInResponses = {
  /**
   * OK
   */
  200: SignInResponse;
};

export type PostAuthEmailPasswordSignInResponse =
  PostAuthEmailPasswordSignInResponses[keyof PostAuthEmailPasswordSignInResponses];

export type PostAuthEmailPasswordSignUpData = {
  /**
   * Sign up request
   */
  body: SignUpRequest;
  path?: never;
  query?: never;
  url: '/auth/email-password/sign-up';
};

export type PostAuthEmailPasswordSignUpErrors = {
  /**
   * Bad request
   */
  400: string;
};

export type PostAuthEmailPasswordSignUpError =
  PostAuthEmailPasswordSignUpErrors[keyof PostAuthEmailPasswordSignUpErrors];

export type PostAuthEmailPasswordSignUpResponses = {
  /**
   * Created
   */
  201: SignUpResponse;
};

export type PostAuthEmailPasswordSignUpResponse =
  PostAuthEmailPasswordSignUpResponses[keyof PostAuthEmailPasswordSignUpResponses];

export type GetAuthEmailPasswordVerifyEmailData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Verification token
     */
    token: string;
    /**
     * Callback URL
     */
    callback_url?: string;
  };
  url: '/auth/email-password/verify-email';
};

export type GetAuthEmailPasswordVerifyEmailErrors = {
  /**
   * Bad request
   */
  400: string;
};

export type GetAuthEmailPasswordVerifyEmailError =
  GetAuthEmailPasswordVerifyEmailErrors[keyof GetAuthEmailPasswordVerifyEmailErrors];

export type GetAuthEmailPasswordVerifyEmailResponses = {
  /**
   * Email verified successfully
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetAuthEmailPasswordVerifyEmailResponse =
  GetAuthEmailPasswordVerifyEmailResponses[keyof GetAuthEmailPasswordVerifyEmailResponses];

export type GetAuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/me';
};

export type GetAuthMeErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
  /**
   * OK
   */
  200: GetMeResponse;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type PostAuthSignOutData = {
  /**
   * Sign out request
   */
  body?: SignOutRequest;
  path?: never;
  query?: never;
  url: '/auth/sign-out';
};

export type PostAuthSignOutErrors = {
  /**
   * Unauthorized
   */
  401: string;
};

export type PostAuthSignOutError =
  PostAuthSignOutErrors[keyof PostAuthSignOutErrors];

export type PostAuthSignOutResponses = {
  /**
   * OK
   */
  200: SignOutResponse;
};

export type PostAuthSignOutResponse =
  PostAuthSignOutResponses[keyof PostAuthSignOutResponses];
