// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {});
};

export type GetApiHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/health";
};

export type GetApiHealthErrors = {
  /**
   * Bad Request
   */
  400: {
    message: string;
  };
};

export type GetApiHealthError = GetApiHealthErrors[keyof GetApiHealthErrors];

export type GetApiHealthResponses = {
  /**
   * Success
   */
  200: string;
};

export type GetApiHealthResponse =
  GetApiHealthResponses[keyof GetApiHealthResponses];

export type GetApiTodosData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/todos";
};

export type GetApiTodosErrors = {
  /**
   * Bad Request
   */
  400: {
    message: string;
  };
  /**
   * Internal Server Error
   */
  500: {
    message: string;
  };
};

export type GetApiTodosError = GetApiTodosErrors[keyof GetApiTodosErrors];

export type GetApiTodosResponses = {
  /**
   * Success
   */
  200: Array<{
    completed: boolean;
    created_at: string;
    id: number;
    text: string;
    updated_at: string;
  }>;
};

export type GetApiTodosResponse =
  GetApiTodosResponses[keyof GetApiTodosResponses];

export type PostApiTodosData = {
  body: {
    completed?: boolean | null;
    text: string;
  };
  path?: never;
  query?: never;
  url: "/api/todos";
};

export type PostApiTodosErrors = {
  /**
   * Bad Request
   */
  400: {
    message: string;
  };
  /**
   * Internal Server Error
   */
  500: {
    message: string;
  };
};

export type PostApiTodosError = PostApiTodosErrors[keyof PostApiTodosErrors];

export type PostApiTodosResponses = {
  /**
   * Created
   */
  201: {
    completed: boolean;
    created_at: string;
    id: number;
    text: string;
    updated_at: string;
  };
};

export type PostApiTodosResponse =
  PostApiTodosResponses[keyof PostApiTodosResponses];

export type DeleteApiTodosByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/todos/{id}";
};

export type DeleteApiTodosByIdErrors = {
  /**
   * Bad Request
   */
  400: {
    message: string;
  };
  /**
   * Not Found
   */
  404: {
    message: string;
  };
  /**
   * Internal Server Error
   */
  500: {
    message: string;
  };
};

export type DeleteApiTodosByIdError =
  DeleteApiTodosByIdErrors[keyof DeleteApiTodosByIdErrors];

export type DeleteApiTodosByIdResponses = {
  /**
   * Success
   */
  200: {
    message: string;
  };
};

export type DeleteApiTodosByIdResponse =
  DeleteApiTodosByIdResponses[keyof DeleteApiTodosByIdResponses];

export type GetApiTodosByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/todos/{id}";
};

export type GetApiTodosByIdErrors = {
  /**
   * Bad Request
   */
  400: {
    message: string;
  };
  /**
   * Not Found
   */
  404: {
    message: string;
  };
  /**
   * Internal Server Error
   */
  500: {
    message: string;
  };
};

export type GetApiTodosByIdError =
  GetApiTodosByIdErrors[keyof GetApiTodosByIdErrors];

export type GetApiTodosByIdResponses = {
  /**
   * Success
   */
  200: {
    completed: boolean;
    created_at: string;
    id: number;
    text: string;
    updated_at: string;
  };
};

export type GetApiTodosByIdResponse =
  GetApiTodosByIdResponses[keyof GetApiTodosByIdResponses];

export type PutApiTodosByIdData = {
  body: {
    completed?: boolean | null;
    text?: string | null;
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/api/todos/{id}";
};

export type PutApiTodosByIdErrors = {
  /**
   * Bad Request
   */
  400: {
    message: string;
  };
  /**
   * Not Found
   */
  404: {
    message: string;
  };
  /**
   * Internal Server Error
   */
  500: {
    message: string;
  };
};

export type PutApiTodosByIdError =
  PutApiTodosByIdErrors[keyof PutApiTodosByIdErrors];

export type PutApiTodosByIdResponses = {
  /**
   * Success
   */
  200: {
    completed: boolean;
    created_at: string;
    id: number;
    text: string;
    updated_at: string;
  };
};

export type PutApiTodosByIdResponse =
  PutApiTodosByIdResponses[keyof PutApiTodosByIdResponses];
