// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zGetApiHealthData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiTodosData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPostApiTodosData = z.object({
  body: z.object({
    completed: z.optional(z.union([z.boolean(), z.null()])),
    text: z.string().min(5).max(250),
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDeleteApiTodosByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zGetApiTodosByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zPutApiTodosByIdData = z.object({
  body: z.object({
    completed: z.optional(z.union([z.boolean(), z.null()])),
    text: z.optional(z.union([z.string().min(5).max(250), z.null()])),
  }),
  path: z.object({
    id: z.int(),
  }),
  query: z.optional(z.never()),
});
