// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zServerInternalSchemasHealthResponse = z.object({
    arch: z.string().optional(),
    args: z.array(z.string()).optional(),
    date: z.string().optional(),
    memory: z.record(z.string(), z.unknown()).optional(),
    node: z.string().optional(),
    os: z.string().optional(),
    status: z.string().optional(),
    timezone: z.string().optional(),
    timezoneName: z.string().optional(),
    timezoneOffset: z.int().optional(),
    uptime: z.number().optional(),
    version: z.string().optional()
});

export const zServerInternalSchemasTodoPriority = z.enum([
    'low',
    'medium',
    'high'
]);

export const zServerInternalSchemasTodoStatus = z.enum([
    'backlog',
    'todo',
    'in_progress',
    'done',
    'canceled'
]);

export const zServerInternalSchemasCreateTodoRequest = z.object({
    actualHours: z.number().optional(),
    cost: z.number().optional(),
    dueDate: z.string().optional(),
    estimatedHours: z.number().optional(),
    label: z.string().optional(),
    priority: zServerInternalSchemasTodoPriority.optional(),
    progress: z.int().optional(),
    status: zServerInternalSchemasTodoStatus.optional(),
    text: z.string().min(1)
});

export const zServerInternalSchemasTodo = z.object({
    actualHours: z.number().optional(),
    completedAt: z.string().optional(),
    cost: z.number().optional(),
    createdAt: z.string().optional(),
    dueDate: z.string().optional(),
    estimatedHours: z.number().optional(),
    id: z.string().optional(),
    label: z.string().optional(),
    priority: zServerInternalSchemasTodoPriority.optional(),
    progress: z.int().optional(),
    status: zServerInternalSchemasTodoStatus.optional(),
    text: z.string().min(1).optional(),
    updatedAt: z.string().optional()
});

export const zServerInternalSchemasUpdateTodoRequest = z.object({
    actualHours: z.number().optional(),
    completedAt: z.string().optional(),
    cost: z.number().optional(),
    dueDate: z.string().optional(),
    estimatedHours: z.number().optional(),
    label: z.string().optional(),
    priority: zServerInternalSchemasTodoPriority.optional(),
    progress: z.int().optional(),
    status: zServerInternalSchemasTodoStatus.optional(),
    text: z.string().optional()
});

/**
 * Todo creation request
 */
export const zPostApiV1TodosBody = zServerInternalSchemasCreateTodoRequest;

export const zDeleteApiV1TodosByIdPath = z.object({
    id: z.string()
});

export const zGetApiV1TodosByIdPath = z.object({
    id: z.string()
});

/**
 * Todo update request
 */
export const zPutApiV1TodosByIdBody = zServerInternalSchemasUpdateTodoRequest;

export const zPutApiV1TodosByIdPath = z.object({
    id: z.string()
});
