// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const z_server_internal_models_create_todo_request = z.object({
    actualHours: z.number().gte(0).optional(),
    cost: z.number().gte(0).optional(),
    dueDate: z.iso.date().optional(),
    estimatedHours: z.number().gte(0).optional(),
    label: z.enum([
        'bug',
        'feature',
        'doc'
    ]).optional(),
    priority: z.enum([
        'low',
        'medium',
        'high'
    ]).optional(),
    progress: z.int().gte(0).lte(100).optional(),
    status: z.enum([
        'backlog',
        'todo',
        'in_progress',
        'done',
        'canceled'
    ]).optional(),
    text: z.string().min(1)
});

export const z_server_internal_models_health_response = z.object({
    arch: z.string().optional(),
    args: z.array(z.string()).optional(),
    date: z.string().optional(),
    memory: z.record(z.string(), z.unknown()).optional(),
    node: z.string().optional(),
    os: z.string().optional(),
    status: z.string().optional(),
    timezone: z.string().optional(),
    timezoneName: z.string().optional(),
    timezoneOffset: z.int().optional(),
    uptime: z.number().optional(),
    version: z.string().optional()
});

export const z_server_internal_models_todo_priority = z.enum([
    'low',
    'medium',
    'high'
]);

export const z_server_internal_models_todo_status = z.enum([
    'backlog',
    'todo',
    'in_progress',
    'done',
    'canceled'
]);

export const z_server_internal_models_todo = z.object({
    actualHours: z.number().optional(),
    completedAt: z.iso.date().optional(),
    cost: z.number().optional(),
    createdAt: z.iso.date().optional(),
    dueDate: z.iso.date().optional(),
    estimatedHours: z.number().optional(),
    id: z.string().optional(),
    label: z.string().optional(),
    priority: z_server_internal_models_todo_priority.optional(),
    progress: z.int().optional(),
    status: z_server_internal_models_todo_status.optional(),
    text: z.string().min(1),
    updatedAt: z.iso.date().optional()
});

export const z_server_internal_models_update_todo_request = z.object({
    actualHours: z.number().gte(0).optional(),
    completedAt: z.string().optional(),
    cost: z.number().gte(0).optional(),
    dueDate: z.iso.date().optional(),
    estimatedHours: z.number().gte(0).optional(),
    label: z.enum([
        'bug',
        'feature',
        'doc'
    ]).optional(),
    priority: z.enum([
        'low',
        'medium',
        'high'
    ]).optional(),
    progress: z.int().gte(0).lte(100).optional(),
    status: z.enum([
        'backlog',
        'todo',
        'in_progress',
        'done',
        'canceled'
    ]).optional(),
    text: z.string().min(1).optional()
});

export const z_post_api_v1_todos_body = z_server_internal_models_create_todo_request;

export const z_delete_api_v1_todos_by_id_path = z.object({
    id: z.string()
});

export const z_get_api_v1_todos_by_id_path = z.object({
    id: z.string()
});

export const z_put_api_v1_todos_by_id_body = z_server_internal_models_update_todo_request;

export const z_put_api_v1_todos_by_id_path = z.object({
    id: z.string()
});
