// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/health": {
            "get": {
                "description": "Returns the health status of the server along with uptime and memory usage",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server_internal_models.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/todos": {
            "get": {
                "description": "Retrieves all todo items",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Get all todos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/server_internal_models.Todo"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new todo item with the provided text",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Create a new todo",
                "parameters": [
                    {
                        "description": "Todo creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server_internal_models.CreateTodoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server_internal_models.Todo"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing text",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/todos/{id}": {
            "get": {
                "description": "Retrieves a single todo item by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Get a todo by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server_internal_models.Todo"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Todo not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing todo item by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Update a todo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Todo update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server_internal_models.UpdateTodoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server_internal_models.Todo"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Todo not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a todo item by its ID",
                "tags": [
                    "Todos"
                ],
                "summary": "Delete a todo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Todo not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server_internal_models.CreateTodoRequest": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "actualHours": {
                    "type": "number",
                    "minimum": 0
                },
                "cost": {
                    "type": "number",
                    "minimum": 0
                },
                "dueDate": {
                    "type": "string",
                    "format": "date"
                },
                "estimatedHours": {
                    "type": "number",
                    "minimum": 0
                },
                "label": {
                    "type": "string",
                    "enum": [
                        "bug",
                        "feature",
                        "doc"
                    ]
                },
                "priority": {
                    "enum": [
                        "low",
                        "medium",
                        "high"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/server_internal_models.TodoPriority"
                        }
                    ]
                },
                "progress": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0
                },
                "status": {
                    "enum": [
                        "backlog",
                        "todo",
                        "in_progress",
                        "done",
                        "canceled"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/server_internal_models.TodoStatus"
                        }
                    ]
                },
                "text": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "server_internal_models.HealthResponse": {
            "type": "object",
            "properties": {
                "arch": {
                    "type": "string"
                },
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "date": {
                    "type": "string"
                },
                "memory": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "node": {
                    "type": "string"
                },
                "os": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                },
                "timezoneName": {
                    "type": "string"
                },
                "timezoneOffset": {
                    "type": "integer"
                },
                "uptime": {
                    "type": "number"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "server_internal_models.Todo": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "actualHours": {
                    "type": "number"
                },
                "completedAt": {
                    "type": "string",
                    "format": "date"
                },
                "cost": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string",
                    "format": "date"
                },
                "dueDate": {
                    "type": "string",
                    "format": "date"
                },
                "estimatedHours": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "priority": {
                    "$ref": "#/definitions/server_internal_models.TodoPriority"
                },
                "progress": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/server_internal_models.TodoStatus"
                },
                "text": {
                    "type": "string",
                    "minLength": 1
                },
                "updatedAt": {
                    "type": "string",
                    "format": "date"
                }
            }
        },
        "server_internal_models.TodoPriority": {
            "type": "string",
            "enum": [
                "low",
                "medium",
                "high"
            ],
            "x-enum-varnames": [
                "TodoPriorityLow",
                "TodoPriorityMedium",
                "TodoPriorityHigh"
            ]
        },
        "server_internal_models.TodoStatus": {
            "type": "string",
            "enum": [
                "backlog",
                "todo",
                "in_progress",
                "done",
                "canceled"
            ],
            "x-enum-varnames": [
                "TodoStatusBacklog",
                "TodoStatusTodo",
                "TodoStatusInProgress",
                "TodoStatusDone",
                "TodoStatusCanceled"
            ]
        },
        "server_internal_models.UpdateTodoRequest": {
            "type": "object",
            "properties": {
                "actualHours": {
                    "type": "number",
                    "minimum": 0
                },
                "completedAt": {
                    "type": "string"
                },
                "cost": {
                    "type": "number",
                    "minimum": 0
                },
                "dueDate": {
                    "type": "string",
                    "format": "date"
                },
                "estimatedHours": {
                    "type": "number",
                    "minimum": 0
                },
                "label": {
                    "type": "string",
                    "enum": [
                        "bug",
                        "feature",
                        "doc"
                    ]
                },
                "priority": {
                    "enum": [
                        "low",
                        "medium",
                        "high"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/server_internal_models.TodoPriority"
                        }
                    ]
                },
                "progress": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0
                },
                "status": {
                    "enum": [
                        "backlog",
                        "todo",
                        "in_progress",
                        "done",
                        "canceled"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/server_internal_models.TodoStatus"
                        }
                    ]
                },
                "text": {
                    "type": "string",
                    "minLength": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
