/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authDashboardRouteImport } from './routes/(auth)/dashboard'
import { Route as authAdminRouteRouteImport } from './routes/(auth)/admin/route'
import { Route as authAdminIndexRouteImport } from './routes/(auth)/admin/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authDashboardRoute = authDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authRouteRoute,
} as any)
const authAdminRouteRoute = authAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authRouteRoute,
} as any)
const authAdminIndexRoute = authAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof authAdminRouteRouteWithChildren
  '/dashboard': typeof authDashboardRoute
  '/admin/': typeof authAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof authDashboardRoute
  '/admin': typeof authAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(auth)/admin': typeof authAdminRouteRouteWithChildren
  '/(auth)/dashboard': typeof authDashboardRoute
  '/(auth)/admin/': typeof authAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/admin' | '/dashboard' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/login'
    | '/(auth)/admin'
    | '/(auth)/dashboard'
    | '/(auth)/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/dashboard': {
      id: '/(auth)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/admin': {
      id: '/(auth)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authAdminRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/admin/': {
      id: '/(auth)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof authAdminIndexRouteImport
      parentRoute: typeof authAdminRouteRoute
    }
  }
}

interface authAdminRouteRouteChildren {
  authAdminIndexRoute: typeof authAdminIndexRoute
}

const authAdminRouteRouteChildren: authAdminRouteRouteChildren = {
  authAdminIndexRoute: authAdminIndexRoute,
}

const authAdminRouteRouteWithChildren = authAdminRouteRoute._addFileChildren(
  authAdminRouteRouteChildren,
)

interface authRouteRouteChildren {
  authAdminRouteRoute: typeof authAdminRouteRouteWithChildren
  authDashboardRoute: typeof authDashboardRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAdminRouteRoute: authAdminRouteRouteWithChildren,
  authDashboardRoute: authDashboardRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
