/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSettingsRouteImport } from './routes/(auth)/settings'
import { Route as authDashboardRouteImport } from './routes/(auth)/dashboard'
import { Route as authAdminRouteRouteImport } from './routes/(auth)/admin/route'
import { Route as authAdminIndexRouteImport } from './routes/(auth)/admin/index'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSettingsRoute = authSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authRouteRoute,
} as any)
const authDashboardRoute = authDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authRouteRoute,
} as any)
const authAdminRouteRoute = authAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authRouteRoute,
} as any)
const authAdminIndexRoute = authAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof authAdminRouteRouteWithChildren
  '/dashboard': typeof authDashboardRoute
  '/settings': typeof authSettingsRoute
  '/admin/': typeof authAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof authDashboardRoute
  '/settings': typeof authSettingsRoute
  '/admin': typeof authAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/(auth)/admin': typeof authAdminRouteRouteWithChildren
  '/(auth)/dashboard': typeof authDashboardRoute
  '/(auth)/settings': typeof authSettingsRoute
  '/(auth)/admin/': typeof authAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/(auth)/admin'
    | '/(auth)/dashboard'
    | '/(auth)/settings'
    | '/(auth)/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/settings': {
      id: '/(auth)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authSettingsRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/dashboard': {
      id: '/(auth)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/admin': {
      id: '/(auth)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authAdminRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/admin/': {
      id: '/(auth)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof authAdminIndexRouteImport
      parentRoute: typeof authAdminRouteRoute
    }
  }
}

interface authAdminRouteRouteChildren {
  authAdminIndexRoute: typeof authAdminIndexRoute
}

const authAdminRouteRouteChildren: authAdminRouteRouteChildren = {
  authAdminIndexRoute: authAdminIndexRoute,
}

const authAdminRouteRouteWithChildren = authAdminRouteRoute._addFileChildren(
  authAdminRouteRouteChildren,
)

interface authRouteRouteChildren {
  authAdminRouteRoute: typeof authAdminRouteRouteWithChildren
  authDashboardRoute: typeof authDashboardRoute
  authSettingsRoute: typeof authSettingsRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAdminRouteRoute: authAdminRouteRouteWithChildren,
  authDashboardRoute: authDashboardRoute,
  authSettingsRoute: authSettingsRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
